# Generated by Django 2.2.12 on 2021-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default='', max_length=100, verbose_name='信息'),
        ),
    ]
