# Generated by Django 2.2.12 on 2022-01-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
